
CSEC_ROOT = ../..

include Makefile.common

#everything: orig sym
everything: iml verify

all: orig sym

include $(CSEC_ROOT)/mk/main.mk

# don't compile lib with CIL cause fail has varargs
CILLY_FLAGS += --leavealone=lib

clean::
	$(RM) client server
