
CSEC_ROOT = ../..

include Makefile.common

#everything: orig sym
everything: iml pv

all: orig sym

OUTPUTS = iml.all.out pvmodel.out

include $(CSEC_ROOT)/mk/main.mk

# don't compile lib with CIL cause fail has varargs
CILLY_FLAGS += --leavealone=lib

clean::
	$(RM) client server
