
include Makefile.common

CFLAGS += -DVERBOSE 
LDLIBS += -lssl -lcrypto

all: execute

execute: $(P1) $(P2)
	./$(P1) $(P1_CMD) & \
	sleep 1; ./$(P2) $(P2_CMD) & \
	wait

$(P1): $(P1_SRC)

$(P2): $(P2_SRC)

compile: $(P1) $(P2)

clean::
	$(RM) $(P1) $(P2) *.o
