
include Makefile.common


all: execute

execute: $(P1) $(P2)
	./$(P1) $(P1_CMD) & \
	sleep 1; ./$(P2) $(P2_CMD) & \
	wait

$(P1) $(P2): $(P1_SRC) $(P2_SRC)
	$(CC) $(CFLAGS) $(LDFLAGS) $(P1_SRC) $(LDLIBS) -o $(P1)
	$(CC) $(CFLAGS) $(LDFLAGS) $(P2_SRC) $(LDLIBS) -o $(P2)

compile: $(P1) $(P2)

clean::
	$(RM) $(P1) $(P2) *.o
