
# Makes the model smaller
# CFLAGS += -DVERBOSE 
LDLIBS += -lssl -lcrypto

P1 = bob
P2 = alice

P1_SRC = proxies.c primitives_crypt.c common.c lib.c bob.c
P2_SRC = proxies.c primitives_crypt.c common.c lib.c alice.c
