
CSEC_ROOT = ../..

include Makefile.common

# for simple make call
everything: iml pv
#everything: iml verify_full

# for eclipse
all: sym

include $(CSEC_ROOT)/mk/main.mk

clean::
	$(RM) RPC
