
CSEC_ROOT = ../..

include Makefile.common

all: iml cv pv

eclipse-all: orig sym

PROXY_LIBS = $(PROXIES)/libsystem-proxies.a $(PROXIES)/libopenssl-proxies.a $(PROXIES)/libcrestify.a

BUILD_CMD = $(MAKE) -f Makefile.run compile CC="$(CC)" CFLAGS="$(CFLAGS)" LDLIBS="$(LDLIBS)"

include $(CSEC_ROOT)/mk/main.mk
