 
CFLAGS += -DVERBOSE 
LDLIBS += -lssl -lcrypto
 
# $(shell find -name "*.c" -not -name "*.cil.c")
SRC := $(filter-out $(wildcard *.cil.c), $(wildcard *.c))

P1 = RPC.server
P2 = RPC.client

P1_CMD = server
P2_CMD = client

P1_SRC = $(SRC)
P2_SRC = $(SRC)
