 
CFLAGS += -DVERBOSE 
LDLIBS += -lssl -lcrypto
 
# $(shell find -name "*.c" -not -name "*.cil.c")
SRC := ProgrammingInterface.c RPC.c RPC_funs.c RPC_net.c

P1 = server.exe
P2 = client.exe

P1_CMD = server
P2_CMD = client

P1_SRC = $(SRC)
P2_SRC = $(SRC)
