
all: execute

include Makefile.common

execute: $(P1) $(P2)
	./$(P1) $(P1_CMD) & \
	sleep 1; ./$(P2) $(P2_CMD) & \
	wait

logs: compile # $(P1) $(P2)
	./$(P1) $(P1_CMD) > server.log & \
	sleep 1; ./$(P2) $(P2_CMD) > client.log &\
	wait

$(P1) $(P2): $(P1_SRC) $(P2_SRC)
	$(CC) $(CFLAGS) $(LDFLAGS) $(P1_SRC) $(LDLIBS) -o $(P1)
	$(CC) $(CFLAGS) $(LDFLAGS) $(P2_SRC) $(LDLIBS) -o $(P2)

compile: $(P1) $(P2)

clean:
	$(RM) $(P1) $(P2)

