/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

void __CrestInit(void) ;
extern void __CrestDone(void)  __attribute__((__crest_skip__)) ;
extern void __CrestLocation(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestIndexOffset(void)  __attribute__((__crest_skip__)) ;
extern void __CrestFieldOffset(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadStackPtr(char const   *name )  __attribute__((__crest_skip__)) ;
extern void __CrestSetPtrStep(void)  __attribute__((__crest_skip__)) ;
extern void __CrestSetLen(void)  __attribute__((__crest_skip__)) ;
extern void __CrestLoadTypeSize(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadChar(char chrVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadString(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadCString(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadMem(void)  __attribute__((__crest_skip__)) ;
extern void __CrestLoadInt(long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(void)  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(char const   *name , void (*funPtr)() )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestNondet(void)  __attribute__((__crest_skip__)) ;
extern void __CrestUnmute(void)  __attribute__((__crest_skip__)) ;
extern void __CrestMute(void)  __attribute__((__crest_skip__)) ;
extern void __CrestSimplify(long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApplyN(char const   *op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClear(long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestInvoke(void (*funPtr)() )  __attribute__((__crest_skip__)) ;
//#line  211 "/usr/lib64/gcc/x86_64-suse-linux/4.5/include/stddef.h"
typedef unsigned long size_t;
//#line  28 "common.h"
void readenv(unsigned char const   *buf , size_t *len , char const   *s ) ;
//#line  30
void make_sym(unsigned char const   *buf , size_t len , char const   *s ) ;
//#line  32
void make_str_sym(char const   *str , char const   *s ) ;
//#line  33
void event0(char const   *s ) ;
//#line  34
void event1(char const   *s , unsigned char const   *buf , size_t len ) ;
//#line  35
void event2(char const   *s , unsigned char const   *buf1 , size_t len1 , unsigned char const   *buf2 ,
            size_t len2 ) ;
//#line  36 "interface.h"
extern void load_buf(unsigned char const   *buf , size_t len , char const   *hint ) ;
//#line  48
extern void symL(char const   *sym , char const   *hint , size_t len , int deterministic ) ;
//#line  49
extern void symN(char const   *sym , char const   *hint , size_t *len , int deterministic ) ;
//#line  51
extern void var(char const   *name , unsigned char const   *buf , unsigned char const   *len ,
                size_t lenlen ) ;
//#line  59
extern void store_buf(unsigned char const   *buf ) ;
//#line  61
extern void store_all(char const   *buf ) ;
//#line  68
extern void event() ;
//#line  12 "common.c"
void readenv(unsigned char const   *buf , size_t *len , char const   *s ) 
{ 

  {
  __CrestCall("readenv", (void (*)())(& readenv));
  __CrestLoadStackPtr("common.i:s[3315]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:len[3314]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:buf[3313]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("common.c:26");
  __CrestLoadStackPtr("common.i:s[3315]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:buf[3313]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:len[3314]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )len));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadInt((long long )8);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
//#line  26
  var(s, buf, (unsigned char const   *)len, sizeof(*len));

  {
  __CrestLocation("common.c:12");
  __CrestReturn(1);
//#line  12
  return;
  }
}
}
//#line  29 "common.c"
void make_sym(unsigned char const   *buf , size_t len , char const   *s ) 
{ 

  {
  __CrestCall("make_sym", (void (*)())(& make_sym));
  __CrestLoadStackPtr("common.i:s[3322]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:len[3321]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:buf[3320]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("common.c:31");
  __CrestLoadStackPtr("common.i:s[3322]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:s[3322]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:len[3321]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  31
  symL(s, s, len, 0);
  __CrestLocation("common.c:32");
  __CrestLoadStackPtr("common.i:buf[3320]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  32
  store_buf(buf);

  {
  __CrestLocation("common.c:29");
  __CrestReturn(1);
//#line  29
  return;
  }
}
}
//#line  35 "common.c"
void make_str_sym(char const   *str , char const   *s ) 
{ 

  {
  __CrestCall("make_str_sym", (void (*)())(& make_str_sym));
  __CrestLoadStackPtr("common.i:s[3327]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:str[3326]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("common.c:39");
  __CrestLoadStackPtr("common.i:s[3327]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:s[3327]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("nullPtr");
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  39
  symN(s, s, (size_t *)((void *)0), 0);
  __CrestLocation("common.c:40");
  __CrestLoadStackPtr("common.i:str[3326]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  40
  store_all(str);

  {
  __CrestLocation("common.c:35");
  __CrestReturn(1);
//#line  35
  return;
  }
}
}
//#line  43 "common.c"
void event0(char const   *s ) 
{ 

  {
  __CrestCall("event0", (void (*)())(& event0));
  __CrestLoadStackPtr("common.i:s[3330]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("common.c:45");
  __CrestLoadStackPtr("common.i:s[3330]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:s[3330]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )0);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  45
  symL(s, s, (size_t )0, 0);
  __CrestLocation("common.c:46");
  __CrestLoadCString("event");
  __CrestLoadCString("event");
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )0);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  46
  symL("event", "event", (size_t )0, 0);
  __CrestLocation("common.c:47");
//#line  47
  event();

  {
  __CrestLocation("common.c:43");
  __CrestReturn(1);
//#line  43
  return;
  }
}
}
//#line  50 "common.c"
void event1(char const   *s , unsigned char const   *buf , size_t len ) 
{ 

  {
  __CrestCall("event1", (void (*)())(& event1));
  __CrestLoadStackPtr("common.i:len[3337]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:buf[3336]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:s[3335]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("common.c:52");
  __CrestLoadStackPtr("common.i:buf[3336]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:len[3337]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  52
  load_buf(buf, len, "");
  __CrestLocation("common.c:53");
  __CrestLoadStackPtr("common.i:s[3335]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:s[3335]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )0);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  53
  symL(s, s, (size_t )0, 0);
  __CrestLocation("common.c:54");
  __CrestLoadCString("event");
  __CrestLoadCString("event");
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )0);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  54
  symL("event", "event", (size_t )0, 0);
  __CrestLocation("common.c:55");
//#line  55
  event();

  {
  __CrestLocation("common.c:50");
  __CrestReturn(1);
//#line  50
  return;
  }
}
}
//#line  58 "common.c"
void event2(char const   *s , unsigned char const   *buf1 , size_t len1 , unsigned char const   *buf2 ,
            size_t len2 ) 
{ 

  {
  __CrestCall("event2", (void (*)())(& event2));
  __CrestLoadStackPtr("common.i:len2[3348]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:buf2[3347]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:len1[3346]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:buf1[3345]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("common.i:s[3344]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("common.c:60");
  __CrestLoadStackPtr("common.i:buf1[3345]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:len1[3346]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  60
  load_buf(buf1, len1, "");
  __CrestLocation("common.c:61");
  __CrestLoadStackPtr("common.i:buf2[3347]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:len2[3348]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  61
  load_buf(buf2, len2, "");
  __CrestLocation("common.c:62");
  __CrestLoadStackPtr("common.i:s[3344]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("common.i:s[3344]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )0);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  62
  symL(s, s, (size_t )0, 0);
  __CrestLocation("common.c:63");
  __CrestLoadCString("event");
  __CrestLoadCString("event");
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )0);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  63
  symL("event", "event", (size_t )0, 0);
  __CrestLocation("common.c:64");
//#line  64
  event();

  {
  __CrestLocation("common.c:58");
  __CrestReturn(1);
//#line  58
  return;
  }
}
}
