/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

void __CrestInit(void) ;
extern void __CrestDone(void)  __attribute__((__crest_skip__)) ;
extern void __CrestLocation(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestIndexOffset(void)  __attribute__((__crest_skip__)) ;
extern void __CrestFieldOffset(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadStackPtr(char const   *name )  __attribute__((__crest_skip__)) ;
extern void __CrestSetPtrStep(void)  __attribute__((__crest_skip__)) ;
extern void __CrestSetLen(void)  __attribute__((__crest_skip__)) ;
extern void __CrestLoadTypeSize(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadChar(char chrVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadString(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadCString(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadMem(void)  __attribute__((__crest_skip__)) ;
extern void __CrestStore(void)  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(char const   *name , void (*funPtr)() )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestNondet(void)  __attribute__((__crest_skip__)) ;
extern void __CrestUnmute(void)  __attribute__((__crest_skip__)) ;
extern void __CrestMute(void)  __attribute__((__crest_skip__)) ;
extern void __CrestSimplify(long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApplyN(char const   *op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClear(long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestInvoke(void (*funPtr)() )  __attribute__((__crest_skip__)) ;
//#line  211 "/usr/lib64/gcc/x86_64-suse-linux/4.5/include/stddef.h"
typedef unsigned long size_t;
//#line  36 "interface.h"
void load_buf(unsigned char const   *buf , size_t len , char const   *hint ) ;
//#line  38
void load_all(char const   *buf , char const   *hint ) ;
//#line  39
void load_ctx(void const   *ctx , char const   *attr , char const   *hint ) ;
//#line  40
void load_int(int n , char const   *hint ) ;
//#line  48
void symL(char const   *sym , char const   *hint , size_t len , int deterministic ) ;
//#line  49
void symN(char const   *sym , char const   *hint , size_t *len , int deterministic ) ;
//#line  51
void var(char const   *name , unsigned char const   *buf , unsigned char const   *len ,
         size_t lenlen ) ;
//#line  59
void store_buf(unsigned char const   *buf ) ;
//#line  61
void store_all(char const   *buf ) ;
//#line  62
void store_ctx(void const   *ctx , char const   *attr ) ;
//#line  68
void event(void) ;
//#line  73
void add_to_attr(void const   *ctx , char const   *attr , unsigned char const   *buf ,
                 size_t len ) ;
//#line  78
void set_attr_str(void const   *ctx , char const   *attr , char const   *str ) ;
//#line  79
void set_attr_buf(void const   *ctx , char const   *attr , unsigned char const   *buf ,
                  size_t len ) ;
//#line  80
void set_attr_int(void const   *ctx , char const   *attr , int n ) ;
//#line  82
int get_attr_int(void const   *ctx , char const   *attr ) ;
//#line  88
void copy_ctx(void const   *to , void const   *from ) ;
//#line  89
void copy_attr_ex(void const   *to , char const   *attr_to , void const   *from ,
                  char const   *attr_from ) ;
//#line  90
void copy_attr(void const   *to , void const   *from , char const   *attr ) ;
//#line  98
void clear_attr(void const   *ctx , char const   *attr ) ;
//#line  106
long concrete_val(long n ) ;
//#line  118
void fresh_ptr(int size ) ;
//#line  192 "./crest.h"
extern void __CrestLoadInt(long long val )  __attribute__((__crest_skip__)) ;
//#line  212
extern void CustomReturn() ;
//#line  213
extern void LoadBuf(unsigned char const   *buf , size_t len ) ;
//#line  214
extern void LoadAll(unsigned char const   *buf ) ;
//#line  215
extern void LoadAttr(void const   *ctx , char const   *attr ) ;
//#line  216
extern void LoadInt(int n ) ;
//#line  217
extern void LoadStr(char const   *str ) ;
//#line  218
extern void Sym(char const   *sym ) ;
//#line  219
extern void SymN(char const   *sym , int n ) ;
//#line  220
extern void Dup() ;
//#line  221
extern void Nondet() ;
//#line  222
extern void Done() ;
//#line  223
extern void Event() ;
//#line  224
extern void Append() ;
//#line  225
extern void Hint(char const   *hint ) ;
//#line  226
extern void SetLen(size_t len ) ;
//#line  227
extern void StoreBuf(unsigned char const   *buf ) ;
//#line  228
extern void StoreAll(unsigned char const   *buf ) ;
//#line  229
extern void StoreAttr(void const   *ctx , char const   *attr ) ;
//#line  230
extern void CopyCtx(void const   *to , void const   *from ) ;
//#line  231
extern void StoreRuntimeInt(void const   *ctx , char const   *attr , int n ) ;
//#line  232
extern int LoadRuntimeInt(void const   *ctx , char const   *attr ) ;
//#line  233
extern void NewHeapPtr(size_t buflen ) ;
//#line  12 "symbolic_interface.c"
void load_buf(unsigned char const   *buf , size_t len , char const   *hint ) 
{ 

  {
  __CrestCall("load_buf", (void (*)())(& load_buf));
  __CrestLoadStackPtr("symbolic_interface.i:hint[3446]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:len[3445]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:buf[3444]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:14");
  __CrestLoadStackPtr("symbolic_interface.i:buf[3444]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:len[3445]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  14
  LoadBuf(buf, len);
  __CrestLocation("symbolic_interface.c:15");
  __CrestLoadStackPtr("symbolic_interface.i:hint[3446]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  15
  Hint(hint);

  {
  __CrestLocation("symbolic_interface.c:12");
  __CrestReturn(1);
//#line  12
  return;
  }
}
}
//#line  18 "symbolic_interface.c"
void load_all(char const   *buf , char const   *hint ) 
{ 

  {
  __CrestCall("load_all", (void (*)())(& load_all));
  __CrestLoadStackPtr("symbolic_interface.i:hint[3451]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:buf[3450]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:20");
  __CrestLoadStackPtr("symbolic_interface.i:buf[3450]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )buf));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
//#line  20
  LoadAll((unsigned char const   *)buf);
  __CrestLocation("symbolic_interface.c:21");
  __CrestLoadStackPtr("symbolic_interface.i:hint[3451]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  21
  Hint(hint);

  {
  __CrestLocation("symbolic_interface.c:18");
  __CrestReturn(1);
//#line  18
  return;
  }
}
}
//#line  24 "symbolic_interface.c"
void load_ctx(void const   *ctx , char const   *attr , char const   *hint ) 
{ 

  {
  __CrestCall("load_ctx", (void (*)())(& load_ctx));
  __CrestLoadStackPtr("symbolic_interface.i:hint[3458]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3457]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3456]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:26");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3456]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3457]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  26
  LoadAttr(ctx, attr);
  __CrestLocation("symbolic_interface.c:27");
  __CrestLoadStackPtr("symbolic_interface.i:hint[3458]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  27
  Hint(hint);

  {
  __CrestLocation("symbolic_interface.c:24");
  __CrestReturn(1);
//#line  24
  return;
  }
}
}
//#line  30 "symbolic_interface.c"
void load_int(int n , char const   *hint ) 
{ 

  {
  __CrestCall("load_int", (void (*)())(& load_int));
  __CrestLoadStackPtr("symbolic_interface.i:hint[3463]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:n[3462]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:32");
  __CrestLoadStackPtr("symbolic_interface.i:n[3462]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  32
  LoadInt(n);
  __CrestLocation("symbolic_interface.c:33");
  __CrestLoadStackPtr("symbolic_interface.i:hint[3463]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  33
  Hint(hint);

  {
  __CrestLocation("symbolic_interface.c:30");
  __CrestReturn(1);
//#line  30
  return;
  }
}
}
//#line  36 "symbolic_interface.c"
void symL(char const   *sym , char const   *hint , size_t len , int deterministic ) 
{ 

  {
  __CrestCall("symL", (void (*)())(& symL));
  __CrestLoadStackPtr("symbolic_interface.i:deterministic[3472]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:len[3471]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:hint[3470]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:sym[3469]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:38");
  __CrestLoadStackPtr("symbolic_interface.i:sym[3469]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  38
  Sym(sym);
  __CrestLocation("symbolic_interface.c:39");
  __CrestLoadStackPtr("symbolic_interface.i:len[3471]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  39
  SetLen(len);
  {
  __CrestLocation("symbolic_interface.c:40");
  __CrestLoadStackPtr("symbolic_interface.i:deterministic[3472]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestApplyN("!", 1);
  __CrestSimplify((long long )deterministic);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestDone();
//#line  40
  if (! deterministic) {
    __CrestBranch(1);
    __CrestLocation("symbolic_interface.c:40");
//#line  40
    Nondet();
  } else {
    __CrestBranch(0);
  }
  }
  __CrestLocation("symbolic_interface.c:41");
//#line  41
  Done();
  {
  __CrestLocation("symbolic_interface.c:42");
  __CrestLoadStackPtr("symbolic_interface.i:hint[3470]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )((unsigned long )hint));
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadStackPtr("nullPtr");
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )((unsigned long )((void *)0)));
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestApplyN("!=", 2);
  __CrestSimplify((long long )((unsigned long )hint != (unsigned long )((void *)0)));
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestDone();
//#line  42
  if ((unsigned long )hint != (unsigned long )((void *)0)) {
    __CrestBranch(1);
    __CrestLocation("symbolic_interface.c:42");
    __CrestLoadStackPtr("symbolic_interface.i:hint[3470]");
    __CrestApplyN("ptrLen", 0);
    __CrestSetPtrStep();
    __CrestLoadMem();
//#line  42
    Hint(hint);
  } else {
    __CrestBranch(0);
  }
  }

  {
  __CrestLocation("symbolic_interface.c:36");
  __CrestReturn(1);
//#line  36
  return;
  }
}
}
//#line  45 "symbolic_interface.c"
void symN(char const   *sym , char const   *hint , size_t *len , int deterministic ) 
{ 

  {
  __CrestCall("symN", (void (*)())(& symN));
  __CrestLoadStackPtr("symbolic_interface.i:deterministic[3481]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:len[3480]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:hint[3479]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:sym[3478]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:47");
  __CrestLoadStackPtr("symbolic_interface.i:sym[3478]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  47
  Sym(sym);
  {
  __CrestLocation("symbolic_interface.c:48");
  __CrestLoadStackPtr("symbolic_interface.i:deterministic[3481]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestApplyN("!", 1);
  __CrestSimplify((long long )deterministic);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestDone();
//#line  48
  if (! deterministic) {
    __CrestBranch(1);
    __CrestLocation("symbolic_interface.c:48");
//#line  48
    Nondet();
  } else {
    __CrestBranch(0);
  }
  }
  __CrestLocation("symbolic_interface.c:49");
//#line  49
  Done();
  {
  __CrestLocation("symbolic_interface.c:50");
  __CrestLoadStackPtr("symbolic_interface.i:hint[3479]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )((unsigned long )hint));
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadStackPtr("nullPtr");
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )((unsigned long )((void *)0)));
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestApplyN("!=", 2);
  __CrestSimplify((long long )((unsigned long )hint != (unsigned long )((void *)0)));
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestDone();
//#line  50
  if ((unsigned long )hint != (unsigned long )((void *)0)) {
    __CrestBranch(1);
    __CrestLocation("symbolic_interface.c:50");
    __CrestLoadStackPtr("symbolic_interface.i:hint[3479]");
    __CrestApplyN("ptrLen", 0);
    __CrestSetPtrStep();
    __CrestLoadMem();
//#line  50
    Hint(hint);
  } else {
    __CrestBranch(0);
  }
  }
  {
  __CrestLocation("symbolic_interface.c:52");
  __CrestLoadStackPtr("symbolic_interface.i:len[3480]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )((unsigned long )len));
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadStackPtr("nullPtr");
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )((unsigned long )((void *)0)));
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestApplyN("!=", 2);
  __CrestSimplify((long long )((unsigned long )len != (unsigned long )((void *)0)));
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestDone();
//#line  52
  if ((unsigned long )len != (unsigned long )((void *)0)) {
    __CrestBranch(1);
    __CrestLocation("symbolic_interface.c:54");
//#line  54
    Dup();
    __CrestLocation("symbolic_interface.c:55");
    __CrestLoadCString("len");
    __CrestLoadInt((long long )1);
    __CrestLoadInt((long long )4);
    __CrestSetLen();
//#line  55
    SymN("len", 1);
    __CrestLocation("symbolic_interface.c:56");
    __CrestLoadInt((long long )8);
    __CrestLoadInt((long long )8);
    __CrestSetLen();
//#line  56
    SetLen(sizeof(*len));
    __CrestLocation("symbolic_interface.c:57");
//#line  57
    Done();
    __CrestLocation("symbolic_interface.c:58");
    __CrestLoadCString("len");
//#line  58
    Hint("len");
    __CrestLocation("symbolic_interface.c:59");
    __CrestLoadStackPtr("symbolic_interface.i:len[3480]");
    __CrestApplyN("ptrLen", 0);
    __CrestSetPtrStep();
    __CrestLoadMem();
    __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
    __CrestApplyN("castToPtr", 2);
    __CrestSimplify((long long )((unsigned long )len));
    __CrestApplyN("ptrLen", 0);
    __CrestSetLen();
    __CrestLoadInt((long long )1);
    __CrestSetPtrStep();
    __CrestDone();
//#line  59
    StoreBuf((unsigned char const   *)len);
  } else {
    __CrestBranch(0);
  }
  }

  {
  __CrestLocation("symbolic_interface.c:45");
  __CrestReturn(1);
//#line  45
  return;
  }
}
}
//#line  63 "symbolic_interface.c"
void var(char const   *name , unsigned char const   *buf , unsigned char const   *len ,
         size_t lenlen ) 
{ 

  {
  __CrestCall("var", (void (*)())(& var));
  __CrestLoadStackPtr("symbolic_interface.i:lenlen[3490]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:len[3489]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:buf[3488]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:name[3487]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:65");
  __CrestLoadStackPtr("symbolic_interface.i:name[3487]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  65
  LoadStr(name);
  __CrestLocation("symbolic_interface.c:66");
  __CrestLoadCString("var");
//#line  66
  Sym("var");
  __CrestLocation("symbolic_interface.c:67");
//#line  67
  Done();
  __CrestLocation("symbolic_interface.c:68");
  __CrestLoadStackPtr("symbolic_interface.i:name[3487]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  68
  Hint(name);
  __CrestLocation("symbolic_interface.c:70");
//#line  70
  Dup();
  __CrestLocation("symbolic_interface.c:71");
  __CrestLoadCString("len");
  __CrestLoadInt((long long )1);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  71
  SymN("len", 1);
  __CrestLocation("symbolic_interface.c:72");
  __CrestLoadStackPtr("symbolic_interface.i:lenlen[3490]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  72
  SetLen(lenlen);
  __CrestLocation("symbolic_interface.c:73");
//#line  73
  Done();
  __CrestLocation("symbolic_interface.c:74");
  __CrestLoadCString("len");
//#line  74
  Hint("len");
  __CrestLocation("symbolic_interface.c:76");
  __CrestLoadStackPtr("symbolic_interface.i:len[3489]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  76
  StoreBuf(len);
  __CrestLocation("symbolic_interface.c:77");
  __CrestLoadStackPtr("symbolic_interface.i:buf[3488]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  77
  StoreBuf(buf);

  {
  __CrestLocation("symbolic_interface.c:63");
  __CrestReturn(1);
//#line  63
  return;
  }
}
}
//#line  80 "symbolic_interface.c"
void store_buf(unsigned char const   *buf ) 
{ 

  {
  __CrestCall("store_buf", (void (*)())(& store_buf));
  __CrestLoadStackPtr("symbolic_interface.i:buf[3493]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:82");
  __CrestLoadStackPtr("symbolic_interface.i:buf[3493]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  82
  StoreBuf(buf);

  {
  __CrestLocation("symbolic_interface.c:80");
  __CrestReturn(1);
//#line  80
  return;
  }
}
}
//#line  85 "symbolic_interface.c"
void store_all(char const   *buf ) 
{ 

  {
  __CrestCall("store_all", (void (*)())(& store_all));
  __CrestLoadStackPtr("symbolic_interface.i:buf[3496]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:87");
  __CrestLoadStackPtr("symbolic_interface.i:buf[3496]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )buf));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
//#line  87
  StoreAll((unsigned char const   *)buf);

  {
  __CrestLocation("symbolic_interface.c:85");
  __CrestReturn(1);
//#line  85
  return;
  }
}
}
//#line  90 "symbolic_interface.c"
void store_ctx(void const   *ctx , char const   *attr ) 
{ 

  {
  __CrestCall("store_ctx", (void (*)())(& store_ctx));
  __CrestLoadStackPtr("symbolic_interface.i:attr[3501]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3500]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:92");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3500]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3501]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  92
  StoreAttr(ctx, attr);

  {
  __CrestLocation("symbolic_interface.c:90");
  __CrestReturn(1);
//#line  90
  return;
  }
}
}
//#line  102 "symbolic_interface.c"
void event(void) 
{ 

  {
  __CrestCall("event", & event);
  __CrestLocation("symbolic_interface.c:104");
//#line  104
  Event();

  {
  __CrestLocation("symbolic_interface.c:102");
  __CrestReturn(1);
//#line  102
  return;
  }
}
}
//#line  107 "symbolic_interface.c"
void add_to_attr(void const   *ctx , char const   *attr , unsigned char const   *buf ,
                 size_t len ) 
{ 

  {
  __CrestCall("add_to_attr", (void (*)())(& add_to_attr));
  __CrestLoadStackPtr("symbolic_interface.i:len[3511]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:buf[3510]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3509]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3508]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:109");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3508]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3509]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  109
  LoadAttr(ctx, attr);
  __CrestLocation("symbolic_interface.c:110");
  __CrestLoadStackPtr("symbolic_interface.i:buf[3510]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:len[3511]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  110
  LoadBuf(buf, len);
  __CrestLocation("symbolic_interface.c:111");
//#line  111
  Append();
  __CrestLocation("symbolic_interface.c:112");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3508]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3509]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  112
  StoreAttr(ctx, attr);

  {
  __CrestLocation("symbolic_interface.c:107");
  __CrestReturn(1);
//#line  107
  return;
  }
}
}
//#line  118 "symbolic_interface.c"
void set_attr_str(void const   *ctx , char const   *attr , char const   *str ) 
{ 

  {
  __CrestCall("set_attr_str", (void (*)())(& set_attr_str));
  __CrestLoadStackPtr("symbolic_interface.i:str[3518]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3517]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3516]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:120");
  __CrestLoadStackPtr("symbolic_interface.i:str[3518]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  120
  LoadStr(str);
  __CrestLocation("symbolic_interface.c:121");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3516]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3517]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  121
  StoreAttr(ctx, attr);

  {
  __CrestLocation("symbolic_interface.c:118");
  __CrestReturn(1);
//#line  118
  return;
  }
}
}
//#line  124 "symbolic_interface.c"
void set_attr_buf(void const   *ctx , char const   *attr , unsigned char const   *buf ,
                  size_t len ) 
{ 

  {
  __CrestCall("set_attr_buf", (void (*)())(& set_attr_buf));
  __CrestLoadStackPtr("symbolic_interface.i:len[3527]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:buf[3526]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3525]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3524]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:126");
  __CrestLoadStackPtr("symbolic_interface.i:buf[3526]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:len[3527]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  126
  LoadBuf(buf, len);
  __CrestLocation("symbolic_interface.c:127");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3524]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3525]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  127
  StoreAttr(ctx, attr);

  {
  __CrestLocation("symbolic_interface.c:124");
  __CrestReturn(1);
//#line  124
  return;
  }
}
}
//#line  130 "symbolic_interface.c"
void set_attr_int(void const   *ctx , char const   *attr , int n ) 
{ 

  {
  __CrestCall("set_attr_int", (void (*)())(& set_attr_int));
  __CrestLoadStackPtr("symbolic_interface.i:n[3534]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3533]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3532]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:132");
  __CrestLoadStackPtr("symbolic_interface.i:n[3534]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  132
  LoadInt(n);
  __CrestLocation("symbolic_interface.c:133");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3532]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3533]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  133
  StoreAttr(ctx, attr);
  __CrestLocation("symbolic_interface.c:135");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3532]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3533]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:n[3534]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  135
  StoreRuntimeInt(ctx, attr, n);

  {
  __CrestLocation("symbolic_interface.c:130");
  __CrestReturn(1);
//#line  130
  return;
  }
}
}
//#line  138 "symbolic_interface.c"
int get_attr_int(void const   *ctx , char const   *attr ) 
{ int tmp ;

  {
  __CrestCall("get_attr_int", (void (*)())(& get_attr_int));
  __CrestLoadStackPtr("symbolic_interface.i:attr[3539]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3538]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:140");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3538]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3539]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  140
  LoadAttr(ctx, attr);
  __CrestLocation("symbolic_interface.c:141");
//#line  141
  CustomReturn();
  __CrestLocation("symbolic_interface.c:142");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3538]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3539]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  142
  tmp = LoadRuntimeInt(ctx, attr);
  __CrestLoadStackPtr("symbolic_interface.i:tmp[3540]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  {
  __CrestLocation("symbolic_interface.c:142");
  __CrestLoadStackPtr("symbolic_interface.i:tmp[3540]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  142
  return (tmp);
  }
}
}
//#line  145 "symbolic_interface.c"
void clear_attr(void const   *ctx , char const   *attr ) 
{ 

  {
  __CrestCall("clear_attr", (void (*)())(& clear_attr));
  __CrestLoadStackPtr("symbolic_interface.i:attr[3545]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3544]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:147");
  __CrestLoadStackPtr("symbolic_interface.i:ctx[3544]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3545]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  147
  set_attr_str(ctx, attr, "");

  {
  __CrestLocation("symbolic_interface.c:145");
  __CrestReturn(1);
//#line  145
  return;
  }
}
}
//#line  150 "symbolic_interface.c"
void copy_ctx(void const   *to , void const   *from ) 
{ 

  {
  __CrestCall("copy_ctx", (void (*)())(& copy_ctx));
  __CrestLoadStackPtr("symbolic_interface.i:from[3550]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:to[3549]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:152");
  __CrestLoadStackPtr("symbolic_interface.i:to[3549]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:from[3550]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  152
  CopyCtx(to, from);

  {
  __CrestLocation("symbolic_interface.c:150");
  __CrestReturn(1);
//#line  150
  return;
  }
}
}
//#line  155 "symbolic_interface.c"
void copy_attr_ex(void const   *to , char const   *attr_to , void const   *from ,
                  char const   *attr_from ) 
{ 

  {
  __CrestCall("copy_attr_ex", (void (*)())(& copy_attr_ex));
  __CrestLoadStackPtr("symbolic_interface.i:attr_from[3559]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:from[3558]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:attr_to[3557]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:to[3556]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:157");
  __CrestLoadStackPtr("symbolic_interface.i:from[3558]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr_from[3559]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  157
  LoadAttr(from, attr_from);
  __CrestLocation("symbolic_interface.c:158");
  __CrestLoadStackPtr("symbolic_interface.i:to[3556]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr_to[3557]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  158
  StoreAttr(to, attr_to);

  {
  __CrestLocation("symbolic_interface.c:155");
  __CrestReturn(1);
//#line  155
  return;
  }
}
}
//#line  161 "symbolic_interface.c"
void copy_attr(void const   *to , void const   *from , char const   *attr ) 
{ 

  {
  __CrestCall("copy_attr", (void (*)())(& copy_attr));
  __CrestLoadStackPtr("symbolic_interface.i:attr[3566]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:from[3565]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("symbolic_interface.i:to[3564]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:163");
  __CrestLoadStackPtr("symbolic_interface.i:to[3564]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3566]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:from[3565]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("symbolic_interface.i:attr[3566]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  163
  copy_attr_ex(to, attr, from, attr);

  {
  __CrestLocation("symbolic_interface.c:161");
  __CrestReturn(1);
//#line  161
  return;
  }
}
}
//#line  166 "symbolic_interface.c"
long concrete_val(long n ) 
{ 

  {
  __CrestCall("concrete_val", (void (*)())(& concrete_val));
  __CrestLoadStackPtr("symbolic_interface.i:n[3569]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
//#line  168
  __CrestLoadInt((long long )n);
  __CrestLocation("symbolic_interface.c:169");
//#line  169
  CustomReturn();
  {
  __CrestLocation("symbolic_interface.c:170");
  __CrestLoadStackPtr("symbolic_interface.i:n[3569]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
//#line  170
  return (n);
  }
}
}
//#line  180 "symbolic_interface.c"
void fresh_ptr(int size ) 
{ 

  {
  __CrestCall("fresh_ptr", (void (*)())(& fresh_ptr));
  __CrestLoadStackPtr("symbolic_interface.i:size[3572]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("symbolic_interface.c:182");
  __CrestLoadStackPtr("symbolic_interface.i:size[3572]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )size);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
//#line  182
  NewHeapPtr((size_t )size);

  {
  __CrestLocation("symbolic_interface.c:180");
  __CrestReturn(1);
//#line  180
  return;
  }
}
}
//#line  186 "symbolic_interface.c"
void sym_return(void) 
{ 

  {
  __CrestCall("sym_return", & sym_return);
  __CrestLocation("symbolic_interface.c:188");
//#line  188
  CustomReturn();

  {
  __CrestLocation("symbolic_interface.c:186");
  __CrestReturn(1);
//#line  186
  return;
  }
}
}
