/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

void __CrestInit(void) ;
extern void __CrestDone(void)  __attribute__((__crest_skip__)) ;
extern void __CrestLocation(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestIndexOffset(void)  __attribute__((__crest_skip__)) ;
extern void __CrestFieldOffset(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadStackPtr(char const   *name )  __attribute__((__crest_skip__)) ;
extern void __CrestSetPtrStep(void)  __attribute__((__crest_skip__)) ;
extern void __CrestSetLen(void)  __attribute__((__crest_skip__)) ;
extern void __CrestLoadTypeSize(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadChar(char chrVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadString(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadCString(char const   *strVal )  __attribute__((__crest_skip__)) ;
extern void __CrestLoadMem(void)  __attribute__((__crest_skip__)) ;
extern void __CrestLoadInt(long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(void)  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(char const   *name , void (*funPtr)() )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestNondet(void)  __attribute__((__crest_skip__)) ;
extern void __CrestUnmute(void)  __attribute__((__crest_skip__)) ;
extern void __CrestMute(void)  __attribute__((__crest_skip__)) ;
extern void __CrestSimplify(long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClear(long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestInvoke(void (*funPtr)() )  __attribute__((__crest_skip__)) ;
//#line  211 "/usr/lib64/gcc/x86_64-suse-linux/4.5/include/stddef.h"
typedef unsigned long size_t;
//#line  180 "/usr/include/bits/types.h"
typedef long __ssize_t;
//#line  110 "/usr/include/sys/types.h"
typedef __ssize_t ssize_t;
//#line  471 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
static  __attribute__((__nothrow__)) void *__crest_malloc_opaque(size_t __size )  __attribute__((__malloc__)) ;
static void *__crest_malloc_opaque(size_t __size ) 
{ void *__crest_ret ;

  {
  __CrestClear(1);
  __CrestLoadStackPtr("malloc()");
  __CrestNondet();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestMute();
  __crest_ret = malloc(__size);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  485
extern  __attribute__((__nothrow__)) void *realloc(void *__ptr , size_t __size )  __attribute__((__warn_unused_result__)) ;
static  __attribute__((__nothrow__)) void *__crest_realloc_opaque(void *__ptr , size_t __size )  __attribute__((__warn_unused_result__)) ;
static void *__crest_realloc_opaque(void *__ptr , size_t __size ) 
{ void *__crest_ret ;

  {
  __CrestClear(2);
  __CrestLoadStackPtr("realloc()");
  __CrestNondet();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestMute();
  __crest_ret = realloc(__ptr, __size);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  181 "crest.h"
extern void __CrestApplyN(char const   * , long long  )  __attribute__((__crest_skip__)) ;
//#line  212
extern void CustomReturn() ;
//#line  233
extern void NewHeapPtr(size_t buflen ) ;
//#line  43 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) void *memcpy(void * __restrict  __dest , void const   * __restrict  __src ,
                                                  size_t __n )  __attribute__((__nonnull__(1,2))) ;
static  __attribute__((__nothrow__)) void *__crest_memcpy_opaque(void * __restrict  __dest ,
                                                                 void const   * __restrict  __src ,
                                                                 size_t __n )  __attribute__((__nonnull__(1,2))) ;
static void *__crest_memcpy_opaque(void * __restrict  __dest , void const   * __restrict  __src ,
                                   size_t __n ) 
{ void *__crest_ret ;

  {
  __CrestClear(3);
  __CrestLoadStackPtr("memcpy()");
  __CrestNondet();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestMute();
  __crest_ret = memcpy(__dest, __src, __n);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  48
extern  __attribute__((__nothrow__)) void *memmove(void *__dest , void const   *__src ,
                                                   size_t __n )  __attribute__((__nonnull__(1,2))) ;
static  __attribute__((__nothrow__)) void *__crest_memmove_opaque(void *__dest , void const   *__src ,
                                                                  size_t __n )  __attribute__((__nonnull__(1,2))) ;
static void *__crest_memmove_opaque(void *__dest , void const   *__src , size_t __n ) 
{ void *__crest_ret ;

  {
  __CrestClear(3);
  __CrestLoadStackPtr("memmove()");
  __CrestNondet();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestMute();
  __crest_ret = memmove(__dest, __src, __n);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  64
extern  __attribute__((__nothrow__)) void *memset(void *__s , int __c , size_t __n )  __attribute__((__nonnull__(1))) ;
static  __attribute__((__nothrow__)) void *__crest_memset_opaque(void *__s , int __c ,
                                                                 size_t __n )  __attribute__((__nonnull__(1))) ;
static void *__crest_memset_opaque(void *__s , int __c , size_t __n ) 
{ void *__crest_ret ;

  {
  __CrestClear(3);
  __CrestLoadStackPtr("memset()");
  __CrestNondet();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestMute();
  __crest_ret = memset(__s, __c, __n);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  67
extern  __attribute__((__nothrow__)) int memcmp(void const   *__s1 , void const   *__s2 ,
                                                size_t __n )  __attribute__((__pure__,
__nonnull__(1,2))) ;
static  __attribute__((__nothrow__)) int __crest_memcmp_opaque(void const   *__s1 ,
                                                               void const   *__s2 ,
                                                               size_t __n )  __attribute__((__pure__,
__nonnull__(1,2))) ;
static int __crest_memcmp_opaque(void const   *__s1 , void const   *__s2 , size_t __n ) 
{ int __crest_ret ;

  {
  __CrestApplyN("memcmp()", 3);
  __CrestNondet();
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestMute();
  __crest_ret = memcmp(__s1, __s2, __n);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  127
extern  __attribute__((__nothrow__)) char *strcpy(char * __restrict  __dest , char const   * __restrict  __src )  __attribute__((__nonnull__(1,2))) ;
static  __attribute__((__nothrow__)) char *__crest_strcpy_opaque(char * __restrict  __dest ,
                                                                 char const   * __restrict  __src )  __attribute__((__nonnull__(1,2))) ;
static char *__crest_strcpy_opaque(char * __restrict  __dest , char const   * __restrict  __src ) 
{ char *__crest_ret ;

  {
  __CrestClear(2);
  __CrestLoadStackPtr("strcpy()");
  __CrestNondet();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestMute();
  __crest_ret = strcpy(__dest, __src);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  142
extern  __attribute__((__nothrow__)) int strcmp(char const   *__s1 , char const   *__s2 )  __attribute__((__pure__,
__nonnull__(1,2))) ;
static  __attribute__((__nothrow__)) int __crest_strcmp_opaque(char const   *__s1 ,
                                                               char const   *__s2 )  __attribute__((__pure__,
__nonnull__(1,2))) ;
static int __crest_strcmp_opaque(char const   *__s1 , char const   *__s2 ) 
{ int __crest_ret ;

  {
  __CrestApplyN("strcmp()", 2);
  __CrestNondet();
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestMute();
  __crest_ret = strcmp(__s1, __s2);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  145
extern  __attribute__((__nothrow__)) int strncmp(char const   *__s1 , char const   *__s2 ,
                                                 size_t __n )  __attribute__((__pure__,
__nonnull__(1,2))) ;
static  __attribute__((__nothrow__)) int __crest_strncmp_opaque(char const   *__s1 ,
                                                                char const   *__s2 ,
                                                                size_t __n )  __attribute__((__pure__,
__nonnull__(1,2))) ;
static int __crest_strncmp_opaque(char const   *__s1 , char const   *__s2 , size_t __n ) 
{ int __crest_ret ;

  {
  __CrestApplyN("strncmp()", 3);
  __CrestNondet();
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestMute();
  __crest_ret = strncmp(__s1, __s2, __n);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  357 "/usr/include/unistd.h"
extern ssize_t read(int __fd , void *__buf , size_t __nbytes ) ;
static ssize_t __crest_read_opaque(int __fd , void *__buf , size_t __nbytes ) 
{ ssize_t __crest_ret ;

  {
  __CrestApplyN("read()", 3);
  __CrestNondet();
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestMute();
  __crest_ret = read(__fd, __buf, __nbytes);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  363
extern ssize_t write(int __fd , void const   *__buf , size_t __n ) ;
static ssize_t __crest_write_opaque(int __fd , void const   *__buf , size_t __n ) 
{ ssize_t __crest_ret ;

  {
  __CrestApplyN("write()", 3);
  __CrestNondet();
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestMute();
  __crest_ret = write(__fd, __buf, __n);
  __CrestUnmute();
  return (__crest_ret);
}
}
//#line  26 "common.h"
extern void proxy_fail(char const   *fmt  , ...) ;
//#line  28 "interface.h"
extern void mute() ;
//#line  29
extern void unmute() ;
//#line  36
extern void load_buf(unsigned char const   *buf , size_t len , char const   *hint ) ;
//#line  38
extern void load_all(char const   *buf , char const   *hint ) ;
//#line  40
extern void load_int(int n , char const   *hint ) ;
//#line  48
extern void symL(char const   *sym , char const   *hint , size_t len , int deterministic ) ;
//#line  49
extern void symN(char const   *sym , char const   *hint , size_t *len , int deterministic ) ;
//#line  59
extern void store_buf(unsigned char const   *buf ) ;
//#line  61
extern void store_all(char const   *buf ) ;
//#line  68
extern void event() ;
//#line  18 "system_proxies.c"
extern int ( __attribute__((__cdecl__)) memcmp_proxy)(void const   *a , void const   *b ,
                                                      size_t len ) 
{ int ret ;
  int tmp ;

  {
  __CrestCall("memcmp_proxy", (void (*)())(& memcmp_proxy));
  __CrestLoadStackPtr("system_proxies.i:len[4169]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:b[4168]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:a[4167]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:20");
  __CrestLoadStackPtr("system_proxies.i:a[4167]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:b[4168]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:len[4169]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  20
  tmp = __crest_memcmp_opaque(a, b, len);
  __CrestLoadStackPtr("system_proxies.i:tmp[4171]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:20");
  __CrestLoadStackPtr("system_proxies.i:tmp[4171]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:ret[4170]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
//#line  20
  ret = tmp;
  __CrestLocation("system_proxies.c:22");
  __CrestLoadStackPtr("system_proxies.i:a[4167]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )a));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:len[4169]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  22
  load_buf((unsigned char const   *)a, len, "");
  __CrestLocation("system_proxies.c:23");
  __CrestLoadStackPtr("system_proxies.i:b[4168]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )b));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:len[4169]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  23
  load_buf((unsigned char const   *)b, len, "");
  __CrestLocation("system_proxies.c:24");
  __CrestLoadCString("cmp");
  __CrestLoadCString("cmp");
  __CrestLoadInt((long long )4);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  24
  symL("cmp", "cmp", sizeof(ret), 1);
  __CrestLocation("system_proxies.c:26");
//#line  26
  CustomReturn();
  {
  __CrestLocation("system_proxies.c:27");
  __CrestLoadStackPtr("system_proxies.i:ret[4170]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  27
  return (ret);
  }
}
}
//#line  30 "system_proxies.c"
extern void *( __attribute__((__cdecl__)) memcpy_proxy)(void *dest , void const   *src ,
                                                        size_t len ) 
{ void *ret ;

  {
  __CrestCall("memcpy_proxy", (void (*)())(& memcpy_proxy));
  __CrestLoadStackPtr("system_proxies.i:len[4178]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:src[4177]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:dest[4176]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:32");
  __CrestLoadStackPtr("system_proxies.i:dest[4176]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:ret[4179]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
//#line  32
  ret = dest;
  __CrestLocation("system_proxies.c:34");
  __CrestLoadStackPtr("system_proxies.i:src[4177]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )src));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:len[4178]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  34
  load_buf((unsigned char const   *)src, len, "");
  __CrestLocation("system_proxies.c:36");
//#line  36
  mute();
  __CrestLocation("system_proxies.c:37");
  __CrestLoadStackPtr("system_proxies.i:dest[4176]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(void ),  __restrict  )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )dest));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:src[4177]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(void const   ),  __restrict  )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )src));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:len[4178]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  37
  ret = __crest_memcpy_opaque((void * __restrict  )dest, (void const   * __restrict  )src,
                              len);
  __CrestLoadStackPtr("system_proxies.i:ret[4179]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:38");
//#line  38
  unmute();
  __CrestLocation("system_proxies.c:40");
  __CrestLoadStackPtr("system_proxies.i:dest[4176]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )dest));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
//#line  40
  store_buf((unsigned char const   *)dest);
  {
  __CrestLocation("system_proxies.c:42");
  __CrestLoadStackPtr("system_proxies.i:ret[4179]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
//#line  42
  return (ret);
  }
}
}
//#line  45 "system_proxies.c"
extern void *( __attribute__((__cdecl__)) memmove_proxy)(void *dest , void const   *src ,
                                                         size_t len ) 
{ void *ret ;

  {
  __CrestCall("memmove_proxy", (void (*)())(& memmove_proxy));
  __CrestLoadStackPtr("system_proxies.i:len[4186]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:src[4185]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:dest[4184]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:47");
  __CrestLoadStackPtr("system_proxies.i:dest[4184]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:ret[4187]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
//#line  47
  ret = dest;
  __CrestLocation("system_proxies.c:49");
  __CrestLoadStackPtr("system_proxies.i:src[4185]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )src));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:len[4186]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  49
  load_buf((unsigned char const   *)src, len, "");
  __CrestLocation("system_proxies.c:51");
//#line  51
  mute();
  __CrestLocation("system_proxies.c:52");
  __CrestLoadStackPtr("system_proxies.i:dest[4184]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:src[4185]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:len[4186]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  52
  ret = __crest_memmove_opaque(dest, src, len);
  __CrestLoadStackPtr("system_proxies.i:ret[4187]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:53");
//#line  53
  unmute();
  __CrestLocation("system_proxies.c:55");
  __CrestLoadStackPtr("system_proxies.i:dest[4184]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )dest));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
//#line  55
  store_buf((unsigned char const   *)dest);
  {
  __CrestLocation("system_proxies.c:57");
  __CrestLoadStackPtr("system_proxies.i:ret[4187]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
//#line  57
  return (ret);
  }
}
}
//#line  60 "system_proxies.c"
int strcmp_proxy(char const   *a , char const   *b ) 
{ int ret ;
  int tmp ;

  {
  __CrestCall("strcmp_proxy", (void (*)())(& strcmp_proxy));
  __CrestLoadStackPtr("system_proxies.i:b[4192]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:a[4191]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:62");
  __CrestLoadStackPtr("system_proxies.i:a[4191]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:b[4192]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  62
  tmp = __crest_strcmp_opaque(a, b);
  __CrestLoadStackPtr("system_proxies.i:tmp[4194]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:62");
  __CrestLoadStackPtr("system_proxies.i:tmp[4194]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:ret[4193]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
//#line  62
  ret = tmp;
  __CrestLocation("system_proxies.c:64");
  __CrestLoadStackPtr("system_proxies.i:a[4191]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )a));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadString("TSPtr(TSBase(char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )((unsigned char const   *)a)));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadCString("");
//#line  64
  load_all((char const   *)((unsigned char const   *)a), "");
//#line  65
  __CrestApplyN("ztp", 1LL);
  __CrestLocation("system_proxies.c:66");
  __CrestLoadStackPtr("system_proxies.i:b[4192]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )b));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadString("TSPtr(TSBase(char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )((unsigned char const   *)b)));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadCString("");
//#line  66
  load_all((char const   *)((unsigned char const   *)b), "");
//#line  67
  __CrestApplyN("ztp", 1LL);
  __CrestLocation("system_proxies.c:68");
  __CrestLoadCString("cmp");
  __CrestLoadCString("cmp");
  __CrestLoadInt((long long )4);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  68
  symL("cmp", "cmp", sizeof(ret), 1);
  __CrestLocation("system_proxies.c:70");
//#line  70
  CustomReturn();
  {
  __CrestLocation("system_proxies.c:71");
  __CrestLoadStackPtr("system_proxies.i:ret[4193]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  71
  return (ret);
  }
}
}
//#line  74 "system_proxies.c"
extern int strncmp_proxy(char const   *a , char const   *b , size_t n ) 
{ int ret ;
  int tmp ;

  {
  __CrestCall("strncmp_proxy", (void (*)())(& strncmp_proxy));
  __CrestLoadStackPtr("system_proxies.i:n[4201]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:b[4200]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:a[4199]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:76");
  __CrestLoadStackPtr("system_proxies.i:a[4199]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:b[4200]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:n[4201]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  76
  tmp = __crest_strncmp_opaque(a, b, n);
  __CrestLoadStackPtr("system_proxies.i:tmp[4203]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:76");
  __CrestLoadStackPtr("system_proxies.i:tmp[4203]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:ret[4202]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
//#line  76
  ret = tmp;
  __CrestLocation("system_proxies.c:78");
  __CrestLoadStackPtr("system_proxies.i:a[4199]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )a));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:n[4201]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  78
  load_buf((unsigned char const   *)a, n, "");
//#line  79
  __CrestApplyN("ztp", 1LL);
  __CrestLocation("system_proxies.c:80");
  __CrestLoadStackPtr("system_proxies.i:b[4200]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )b));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:n[4201]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  80
  load_buf((unsigned char const   *)b, n, "");
//#line  81
  __CrestApplyN("ztp", 1LL);
  __CrestLocation("system_proxies.c:82");
  __CrestLoadCString("cmp");
  __CrestLoadCString("cmp");
  __CrestLoadInt((long long )4);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  82
  symL("cmp", "cmp", sizeof(ret), 1);
  __CrestLocation("system_proxies.c:84");
//#line  84
  CustomReturn();
  {
  __CrestLocation("system_proxies.c:85");
  __CrestLoadStackPtr("system_proxies.i:ret[4202]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  85
  return (ret);
  }
}
}
//#line  88 "system_proxies.c"
extern void *malloc_proxy(size_t size ) 
{ void *ret ;

  {
  __CrestCall("malloc_proxy", (void (*)())(& malloc_proxy));
  __CrestLoadStackPtr("system_proxies.i:size[4206]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:90");
  __CrestLoadStackPtr("nullPtr");
  __CrestLoadStackPtr("system_proxies.i:ret[4207]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
//#line  90
  ret = (void *)0;
  __CrestLocation("system_proxies.c:92");
  __CrestLoadStackPtr("system_proxies.i:size[4206]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  92
  ret = __crest_malloc_opaque(size);
  __CrestLoadStackPtr("system_proxies.i:ret[4207]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:94");
  __CrestLoadStackPtr("system_proxies.i:size[4206]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  94
  NewHeapPtr(size);
  __CrestLocation("system_proxies.c:96");
//#line  96
  CustomReturn();
  {
  __CrestLocation("system_proxies.c:97");
  __CrestLoadStackPtr("system_proxies.i:ret[4207]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
//#line  97
  return (ret);
  }
}
}
//#line  107 "system_proxies.c"
extern void *realloc_proxy(void *ptr , size_t size ) 
{ void *ret ;

  {
  __CrestCall("realloc_proxy", (void (*)())(& realloc_proxy));
  __CrestLoadStackPtr("system_proxies.i:size[4212]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:ptr[4211]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:109");
  __CrestLoadStackPtr("nullPtr");
  __CrestLoadStackPtr("system_proxies.i:ret[4213]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
//#line  109
  ret = (void *)0;
  __CrestLocation("system_proxies.c:111");
  __CrestLoadStackPtr("system_proxies.i:ptr[4211]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:size[4212]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  111
  ret = __crest_realloc_opaque(ptr, size);
  __CrestLoadStackPtr("system_proxies.i:ret[4213]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:113");
  __CrestLoadStackPtr("system_proxies.i:size[4212]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  113
  NewHeapPtr(size);
  __CrestLocation("system_proxies.c:115");
  __CrestLoadStackPtr("system_proxies.i:ret[4213]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )(& ret)));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
//#line  115
  store_buf((unsigned char const   *)(& ret));
  __CrestLocation("system_proxies.c:116");
  __CrestLoadStackPtr("system_proxies.i:ptr[4211]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )ptr));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadCString("");
//#line  116
  load_all((char const   *)ptr, "");
  __CrestLocation("system_proxies.c:117");
  __CrestLoadStackPtr("system_proxies.i:ret[4213]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )ret));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
//#line  117
  store_buf((unsigned char const   *)ret);
  {
  __CrestLocation("system_proxies.c:119");
  __CrestLoadStackPtr("system_proxies.i:ret[4213]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
//#line  119
  return (ret);
  }
}
}
//#line  126 "system_proxies.c"
extern void *memset_proxy(void *s , int c , size_t n ) 
{ void *ret ;
  void *tmp ;

  {
  __CrestCall("memset_proxy", (void (*)())(& memset_proxy));
  __CrestLoadStackPtr("system_proxies.i:n[4220]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:c[4219]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:s[4218]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:128");
  __CrestLoadStackPtr("system_proxies.i:s[4218]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:c[4219]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:n[4220]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  128
  tmp = __crest_memset_opaque(s, c, n);
  __CrestLoadStackPtr("system_proxies.i:tmp[4222]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:128");
  __CrestLoadStackPtr("system_proxies.i:tmp[4222]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:ret[4221]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
//#line  128
  ret = tmp;
  __CrestLocation("system_proxies.c:130");
  __CrestLoadStackPtr("system_proxies.i:s[4218]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:ret[4221]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
//#line  130
  ret = s;
  __CrestLocation("system_proxies.c:132");
  __CrestLoadStackPtr("system_proxies.i:c[4219]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadCString("");
//#line  132
  load_int(c, "");
  __CrestLocation("system_proxies.c:133");
  __CrestLoadCString("replicate");
  __CrestLoadCString("replicate");
  __CrestLoadStackPtr("system_proxies.i:n[4220]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadInt((long long )1);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  133
  symL("replicate", "replicate", n, 1);
  __CrestLocation("system_proxies.c:134");
  __CrestLoadStackPtr("system_proxies.i:s[4218]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )s));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
//#line  134
  store_buf((unsigned char const   *)s);
  {
  __CrestLocation("system_proxies.c:136");
  __CrestLoadStackPtr("system_proxies.i:ret[4221]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
//#line  136
  return (ret);
  }
}
}
//#line  152 "system_proxies.c"
extern ssize_t read_proxy(int fd , void *buf , size_t nbytes ) 
{ ssize_t ret ;
  ssize_t tmp ;

  {
  __CrestCall("read_proxy", (void (*)())(& read_proxy));
  __CrestLoadStackPtr("system_proxies.i:nbytes[4229]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:buf[4228]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:fd[4227]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:154");
  __CrestLoadStackPtr("system_proxies.i:fd[4227]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:buf[4228]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:nbytes[4229]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  154
  tmp = __crest_read_opaque(fd, buf, nbytes);
  __CrestLoadStackPtr("system_proxies.i:tmp[4231]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:154");
  __CrestLoadStackPtr("system_proxies.i:tmp[4231]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:ret[4230]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
//#line  154
  ret = tmp;
  {
  __CrestLocation("system_proxies.c:156");
  __CrestLoadStackPtr("system_proxies.i:ret[4230]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )ret);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:nbytes[4229]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestApplyN("!=", 2);
  __CrestSimplify((long long )((size_t )ret != nbytes));
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestDone();
//#line  156
  if ((size_t )ret != nbytes) {
    __CrestBranch(1);
    __CrestLocation("system_proxies.c:158");
    __CrestLoadCString("read_proxy: ret != nbytes not handled yet");
    __CrestMute();
//#line  158
    proxy_fail("read_proxy: ret != nbytes not handled yet");
    __CrestUnmute();
    __CrestClear(1);
  } else {
    __CrestBranch(0);
  }
  }
  __CrestLocation("system_proxies.c:161");
  __CrestLoadStackPtr("system_proxies.i:nbytes[4229]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSBase(long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )nbytes);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:ret[4230]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
//#line  161
  ret = (ssize_t )nbytes;
  __CrestLocation("system_proxies.c:163");
  __CrestLoadCString("read");
  __CrestLoadCString("msg");
  __CrestLoadStackPtr("system_proxies.i:ret[4230]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )ret);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  163
  symL("read", "msg", (size_t )ret, 0);
  __CrestLocation("system_proxies.c:164");
  __CrestLoadStackPtr("system_proxies.i:buf[4228]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )buf));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
//#line  164
  store_buf((unsigned char const   *)buf);
  {
  __CrestLocation("system_proxies.c:166");
  __CrestLoadStackPtr("system_proxies.i:ret[4230]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
//#line  166
  return (ret);
  }
}
}
//#line  169 "system_proxies.c"
extern ssize_t write_proxy(int fd , void const   *buf , size_t n ) 
{ ssize_t ret ;
  ssize_t tmp ;

  {
  __CrestCall("write_proxy", (void (*)())(& write_proxy));
  __CrestLoadStackPtr("system_proxies.i:n[4238]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:buf[4237]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:fd[4236]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:171");
  __CrestLoadStackPtr("system_proxies.i:fd[4236]");
  __CrestLoadInt((long long )4);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:buf[4237]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:n[4238]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
//#line  171
  tmp = __crest_write_opaque(fd, buf, n);
  __CrestLoadStackPtr("system_proxies.i:tmp[4240]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:171");
  __CrestLoadStackPtr("system_proxies.i:tmp[4240]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadStackPtr("system_proxies.i:ret[4239]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
//#line  171
  ret = tmp;
  {
  __CrestLocation("system_proxies.c:173");
  __CrestLoadStackPtr("system_proxies.i:ret[4239]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )ret);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:n[4238]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestApplyN("!=", 2);
  __CrestSimplify((long long )((size_t )ret != n));
  __CrestLoadInt((long long )4);
  __CrestSetLen();
  __CrestDone();
//#line  173
  if ((size_t )ret != n) {
    __CrestBranch(1);
    __CrestLocation("system_proxies.c:175");
    __CrestLoadCString("write_proxy: ret != n not handled yet");
    __CrestMute();
//#line  175
    proxy_fail("write_proxy: ret != n not handled yet");
    __CrestUnmute();
    __CrestClear(1);
  } else {
    __CrestBranch(0);
  }
  }
  __CrestLocation("system_proxies.c:178");
  __CrestLoadStackPtr("system_proxies.i:n[4238]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSBase(long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )n);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:ret[4239]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestStore();
//#line  178
  ret = (ssize_t )n;
  __CrestLocation("system_proxies.c:180");
  __CrestLoadStackPtr("system_proxies.i:buf[4237]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )buf));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:ret[4239]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSBase(unsigned long )");
  __CrestApplyN("castToInt", 2);
  __CrestSimplify((long long )ret);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
  __CrestDone();
  __CrestLoadCString("msg");
//#line  180
  load_buf((unsigned char const   *)buf, (size_t )ret, "msg");
  __CrestLocation("system_proxies.c:181");
  __CrestLoadCString("write");
  __CrestLoadCString("write");
  __CrestLoadStackPtr("nullPtr");
  __CrestLoadInt((long long )0);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  181
  symN("write", "write", (size_t *)((void *)0), 0);
  __CrestLocation("system_proxies.c:182");
//#line  182
  event();
  {
  __CrestLocation("system_proxies.c:184");
  __CrestLoadStackPtr("system_proxies.i:ret[4239]");
  __CrestLoadInt((long long )8);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestLoadInt((long long )8);
  __CrestSetLen();
//#line  184
  return (ret);
  }
}
}
//#line  190 "system_proxies.c"
extern char *strcpy_proxy(char *dest , char const   *src ) 
{ void *ret ;
  char *tmp ;
  char *__retres5 ;

  {
  __CrestCall("strcpy_proxy", (void (*)())(& strcpy_proxy));
  __CrestLoadStackPtr("system_proxies.i:src[4245]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLoadStackPtr("system_proxies.i:dest[4244]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:192");
  __CrestLoadStackPtr("system_proxies.i:dest[4244]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(char ),  __restrict  )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )dest));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:src[4245]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(char const   ),  __restrict  )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )src));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
//#line  192
  tmp = __crest_strcpy_opaque((char * __restrict  )dest, (char const   * __restrict  )src);
  __CrestLoadStackPtr("system_proxies.i:tmp[4247]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
  __CrestLocation("system_proxies.c:192");
  __CrestLoadStackPtr("system_proxies.i:tmp[4247]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(void ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )tmp));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:ret[4246]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
//#line  192
  ret = (void *)tmp;
  __CrestLocation("system_proxies.c:194");
  __CrestLoadStackPtr("system_proxies.i:dest[4244]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(void ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )dest));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:ret[4246]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
//#line  194
  ret = (void *)dest;
  __CrestLocation("system_proxies.c:196");
  __CrestLoadStackPtr("system_proxies.i:src[4245]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )src));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadString("TSPtr(TSBase(char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )((unsigned char const   *)src)));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadCString("");
//#line  196
  load_all((char const   *)((unsigned char const   *)src), "");
  __CrestLocation("system_proxies.c:197");
  __CrestLoadCString("ztp");
  __CrestLoadCString("ztp");
  __CrestLoadStackPtr("nullPtr");
  __CrestLoadInt((long long )1);
  __CrestLoadInt((long long )4);
  __CrestSetLen();
//#line  197
  symN("ztp", "ztp", (size_t *)((void *)0), 1);
  __CrestLocation("system_proxies.c:198");
  __CrestLoadStackPtr("system_proxies.i:dest[4244]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(unsigned char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )dest));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadString("TSPtr(TSBase(char const   ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )((unsigned char const   *)dest)));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
//#line  198
  store_all((char const   *)((unsigned char const   *)dest));
  __CrestLocation("system_proxies.c:200");
  __CrestLoadStackPtr("system_proxies.i:ret[4246]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestLoadString("TSPtr(TSBase(char ), )");
  __CrestApplyN("castToPtr", 2);
  __CrestSimplify((long long )((unsigned long )ret));
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
  __CrestLoadInt((long long )1);
  __CrestSetPtrStep();
  __CrestDone();
  __CrestLoadStackPtr("system_proxies.i:__retres5[4248]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestStore();
//#line  200
  __retres5 = (char *)ret;
  {
  __CrestLocation("system_proxies.c:190");
  __CrestLoadStackPtr("system_proxies.i:__retres5[4248]");
  __CrestApplyN("ptrLen", 0);
  __CrestSetPtrStep();
  __CrestLoadMem();
  __CrestReturn(0);
  __CrestApplyN("ptrLen", 0);
  __CrestSetLen();
//#line  190
  return (__retres5);
  }
}
}
