
CSEC_ROOT = ../..

include Makefile.common

all: iml cv pv

eclipse-all: compile

PROXY_LIBS = $(PROXIES)/libcrestify.a $(PROXIES)/libsystem-proxies.a $(PROXIES)/libopenssl-proxies.a
PROXY_OBJ = lib_proxy.o

BUILD_CMD = $(MAKE) -f Makefile.run compile CC="$(CC)" CFLAGS="$(CFLAGS)" LDLIBS="$(LDLIBS)"

include $(CSEC_ROOT)/mk/main.mk

clean::
	$(RM) client server
