
CSEC_ROOT = ../..

all: iml cv pv

eclipse-all: compile

include Makefile.common

PROXY_LIBS = $(PROXIES)/libcrestify.a $(PROXIES)/libsystem-proxies.a
PROXY_OBJ = lib_proxy.o net_proxy.o

BUILD_DEPS = $(P1_SRC) $(P2_SRC)
BUILD_CMD = $(MAKE) -f Makefile.run compile CC="$(CC)" CFLAGS="$(CFLAGS)" LDLIBS="$(LDLIBS)"

include $(CSEC_ROOT)/mk/main.mk
	
csec-verify-log: csec-verify.log
csec-verify.log:
	$(MAKE) -f Makefile.csec > $@ 2>&1
