
FILES = client.c server.c lib.c lib.h lib_proxy.c net.c net.h rpc-enc.h  Makefile proxies.conf RPC-enc.v iml.all.good.txt query.in pvmodel.good.txt

# FD: Sorry about the .exe, the fact that the thing compiles everytime I want
# to run it is starting to get on my nerves
P1 = server.exe
P2 = client.exe

P1_SRC = server.c net.c lib.c
P2_SRC = client.c net.c lib.c

P1_CMD = localhost 4433
P2_CMD = localhost localhost 4433 "What is the weather like?"

# The model is smaller without this
# -DVERBOSE 
CFLAGS = -Ipolarssl/include -Igcm -Wall
LDFLAGS = -Lpolarssl/library -Lgcm
LDLIBS = -lminimal -lgcm -ldl 

polarssl: polarssl/library/libminimal.a

polarssl/library/libminimal.a:
	cd polarssl/library; make minimal

gcm: gcm/libgcm.a

gcm/libgcm.a:
	cd gcm; make gcmlib
